version: '3.9'

services:
  core:
    build:
      context: ./core
    container_name: core
    ports:
      - "5001:5001"
    networks:
      - app-network

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "3001:3001"
    depends_on:
      - core
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
